name: dominoes
version: 2.1.0.9

dependencies:
  - base

library:
  exposed-modules: Dominoes
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - containers
  - speculate
  - leancheck-instances
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - dominoes
      - hspec
      - speculate
  
  experiments:
    main: Experiments.hs
    source-dirs: .
    dependencies:
      - containers
      - dominoes
      - speculate
      - leancheck-instances
